name: Build & Publish Docker Images

on:
    push:
        branches: [master]
    release:
        types: [published]

jobs:
    # Build and Publish master branch
    build-and-publish-latest-master:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master' # Running this job only for master branch
        steps:
            - uses: actions/checkout@v2 # Checking out the repo
            - name: Build and Publish latest Docker image
              uses: VaultVulp/gp-docker-action@1.1.7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                  image-name: quantconnect/lean:foundation # Provide only Docker image name, tag will be automatically set to latest
                  dockerfile: DockerfileLeanFoundation
    # Build and Publish tags
    build-and-publish-tag:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags
        steps:
            - uses: actions/checkout@v2
            - name: Build and Publish Tag Docker image
              uses: VaultVulp/gp-docker-action@1.1.7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                  image-name: quantconnect/lean:foundation # Provide only Docker image name
                  dockerfile: DockerfileLeanFoundation
                  extract-git-tag: true # Provide flag to extract Docker image tag from git reference
